### ISSUE TITLE
Gopacket libraries not found

### ISSUE THREAD

**Issue by gregs5** [mikkolehtisalo/brassfork#2]
"go get github.com/mikkolehtisalo/brassfork" results in:

package code.google.com/p/gopacket: unrecognized import path "code.google.com/p/gopacket" (parse https://code.google.com/p/gopacket?go-get=1: no go-import meta tags (meta tag github.com/google/gopacket did not match import path code.google.com/p/gopacket))
package code.google.com/p/gopacket/layers: unrecognized import path "code.google.com/p/gopacket/layers" (parse https://code.google.com/p/gopacket/layers?go-get=1: no go-import meta tags (meta tag github.com/google/gopacket did not match import path code.google.com/p/gopacket/layers))
package code.google.com/p/gopacket/pcap: unrecognized import path "code.google.com/p/gopacket/pcap" (parse https://code.google.com/p/gopacket/pcap?go-get=1: no go-import meta tags (meta tag github.com/google/gopacket did not match import path code.google.com/p/gopacket/pcap

I believe this is due to the (new) location of those libraries being:
"github.com/google/gopacket"
"github.com/google/gopacket/layers"
"github.com/google/gopacket/pcap"

**Comment by gregs5** [comment]
Proposed a fix for this in #1

**Comment by mikkolehtisalo** [comment]
Thanks!
